// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/MsgType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from proto/MsgType.proto</summary>
  public static partial class MsgTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/MsgType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNwcm90by9Nc2dUeXBlLnByb3RvEghQcm90b2NvbCpnCgdNc2dUeXBlEggK",
            "BFplcm8QABIPCgtUZXN0UmVxdWVzdBABEhAKDFRlc3RSZXNwb25zZRACEhYK",
            "EUNyZWF0ZVJvb21SZXF1ZXN0EOkHEhcKEkNyZWF0ZVJvb21SZXNwb25zZRDq",
            "ByoYCglFcnJvckNvZGUSCwoHVW5rbm93bhAAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.MsgType), typeof(global::Protocol.ErrorCode), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// MsgType 游戏ID
  /// </summary>
  public enum MsgType {
    [pbr::OriginalName("Zero")] Zero = 0,
    /// <summary>
    ///22222
    /// </summary>
    [pbr::OriginalName("TestRequest")] TestRequest = 1,
    [pbr::OriginalName("TestResponse")] TestResponse = 2,
    /// <summary>
    ///创建房间
    /// </summary>
    [pbr::OriginalName("CreateRoomRequest")] CreateRoomRequest = 1001,
    [pbr::OriginalName("CreateRoomResponse")] CreateRoomResponse = 1002,
  }

  /// <summary>
  /// ErrorCode 游戏错误码
  /// </summary>
  public enum ErrorCode {
    /// <summary>
    /// 未知错误
    /// </summary>
    [pbr::OriginalName("Unknown")] Unknown = 0,
  }

  #endregion

}

#endregion Designer generated code
